personas = [
    ('Martín', 'Soto', (24, 8, 1990)),
    ('Laura', 'García', (15, 3, 1985)),
    ('Andrés', 'Pérez', (2, 11, 1992)),
    ('Camila', 'López', (7, 1, 1998)),
    ('Javier', 'Torres', (30, 5, 1989)),
    ('Sofía', 'Ramos', (18, 9, 1995)),
    ('Diego', 'Fernández', (25, 12, 1983)),
    ('Lucía', 'Morales', (11, 7, 1991)),
    ('Carlos', 'Ruiz', (4, 10, 1997)),
    ('Valentina', 'Castro', (19, 2, 2000)),
    ('Lucía', 'Oriles', (11, 7, 1991)),
    ('Valentina', 'Ruiz', (4, 10, 1997)),
    ('Valentina', 'Rogelia', (19, 2, 2000))
]



signos_compatibles = {
#   (mujer, hombre)
    ('aries', 'tauro'),
    ('aries', 'geminis'),
    ('aries', 'cancer'),
    ('aries', 'libra'),
    ('aries', 'escorpion'),
    ('aries', 'sagitario'),
    ('aries', 'acuario'),

    ('tauro', 'tauro'),
    ('tauro', 'leo'),
    ('tauro', 'virgo'),
    ('tauro', 'escorpion'),
    ('tauro', 'capricornio'),
    ('tauro', 'piscis'),

    ('geminis', 'aries'),
    ('geminis', 'tauro'),
    ('geminis', 'geminis'),
    ('geminis', 'libra'),
    ('geminis', 'acuario'),
    ('geminis', 'piscis'),

    ('cancer', 'tauro'),
    ('cancer', 'cancer'),
    ('cancer', 'leo'),
    ('cancer', 'virgo'),
    ('cancer', 'libra'),
    ('cancer', 'escorpion'),
    ('cancer', 'piscis'),

    ('leo', 'aries'),
    ('leo', 'tauro'),
    ('leo', 'geminis'),
    ('leo', 'libra'),
    ('leo', 'capricornio'),

    ('virgo', 'tauro'),
    ('virgo', 'cancer'),
    ('virgo', 'leo'),
    ('virgo', 'virgo'),
    ('virgo', 'escorpion'),
    ('virgo', 'capricornio'),
    ('virgo', 'acuario'),
    ('virgo', 'piscis'),

    ('libra', 'aries'),
    ('libra', 'tauro'),
    ('libra', 'geminis'),
    ('libra', 'cancer'),
    ('libra', 'virgo'),
    ('libra', 'escorpion'),
    ('libra', 'acuario'),

    ('escorpion', 'tauro'),
    ('escorpion', 'geminis'),
    ('escorpion', 'cancer'),
    ('escorpion', 'virgo'),
    ('escorpion', 'escorpion'),
    ('escorpion', 'acuario'),
    ('escorpion', 'piscis'),

    ('sagitario', 'aries'),
    ('sagitario', 'geminis'),
    ('sagitario', 'leo'),
    ('sagitario', 'virgo'),
    ('sagitario', 'libra'),
    ('sagitario', 'escorpion'),
    ('sagitario', 'sagitario'),
    ('sagitario', 'capricornio'),
    ('sagitario', 'acuario'),

    ('capricornio', 'tauro'),
    ('capricornio', 'leo'),
    ('capricornio', 'virgo'),
    ('capricornio', 'capricornio'),

    ('acuario', 'aries'),
    ('acuario', 'leo'),
    ('acuario', 'libra'),
    ('acuario', 'sagitario'),
    ('acuario', 'acuario'),
    ('acuario', 'piscis'),

    ('piscis', 'aries'),
    ('piscis', 'tauro'),
    ('piscis', 'cancer'),
    ('piscis', 'libra'),
    ('piscis', 'capricornio'),
    ('piscis', 'piscis'),
}
